### ISSUE TITLE
Windowed mode cannot be resized or relocated

### ISSUE THREAD

**Issue by Nowena** [xan1242/NFSU_WindowedMode#1] opened 2022-10-19 04:13 UTC
The game launches in windowed mode but I cannot modify it all, the only way out is to quit thorugh the game's input/controls and when it is running, I cannot click on anything else. I see the taskbar and apps but I just can't do anything until I exit the game.

**Comment by xan1242** [comment] 2022-10-19 04:27
First of all, read this: https://github.com/xan1242/NFSU_WindowedMode#note

I suggest not to use this anymore, unless you really want relocation... Get the latest WS fix dev build.

Secondly, this is unfortunately a known issue and is caused by the game not reading the mouse in windowed mode.

It's fixable, and it'll get fixed in XtendedInput (and may also be included in WS fix, depending on the situation)

I will probably archive this repo as I don't plan to work on it here anymore.

**Closed as completed by xan1242** 2022-10-19 04:27 UTC
